version: '3.1'

services:
  backend:
    build: 
      context: ./api
    ports:
       - 5000:80
       - 5100:443
    depends_on:
      - database
    environment:
        ASPNETCORE_ENVIRONMENT: Development

  database:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather
    
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  # pgadmin:
  #   image: dpage/pgadmin4:6.9
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #       PGADMIN_DEFAULT_PASSWORD: password
  #       PGADMIN_LISTEN_PORT: 80
  #   ports:
  #       - 15432:80
  #   depends_on:
  #       - database
