version: '3.1'

services:
  backend:
    build: 
      context: ./api
    ports:
       - 5000:80
       - 5100:443
    depends_on:
      - database
    environment:
        ASPNETCORE_ENVIRONMENT: Development

  database:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather
    
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
